version: '3.1'

services:
 mongo-database:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
 app:
   image: startwars:latest
   restart: always
   ports:
     - 8080:8080
   depends_on:
     - "mongo-database"
